# Generated by Django 5.0.6 on 2026-06-05 15:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('LIKE', 'Like'), ('COMMENT', 'Comment'), ('FOLLOW', 'Follow'), ('SOS_RESPONSE', 'SOS Response'), ('BOOKING_REQUEST', 'Booking Request'), ('BOOKING_CONFIRMED', 'Booking Confirmed'), ('BOOKING_COMPLETED', 'Booking Completed'), ('PAYMENT_RECEIVED', 'Payment Received'), ('BADGE_UNLOCK', 'Badge Unlock'), ('POINTS_AWARDED', 'Points Awarded'), ('TIP_VERIFIED', 'Tip Verified'), ('NEW_MESSAGE', 'New Message'), ('SUBSCRIPTION_EXPIRING', 'Subscription Expiring'), ('SHOWCASE_ORDER', 'Showcase Order'), ('SHOWCASE_DELIVERED', 'Showcase Delivered'), ('LEVEL_UP', 'Level Up'), ('REVIEW_RECEIVED', 'Review Received')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('data', models.JSONField(default=dict)),
                ('is_read', models.BooleanField(default=False)),
                ('fcm_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
