# Generated by Django 5.0.6 on 2026-06-20 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('LIKE', 'Like'), ('FOLLOW', 'Follow'), ('SOS_RESPONSE', 'SOS Response'), ('SOS_CREATED', 'SOS Created'), ('SOS_RESOLVED', 'SOS Resolved'), ('SOS_CANCELLED', 'SOS Cancelled'), ('SOS_ESCALATED', 'SOS Escalated'), ('SOS_INTEREST_REGISTERED', 'SOS Interest Registered'), ('SOS_MULTIPLE_RESPONDERS', 'SOS Multiple Responders'), ('SOS_RESPONDER_CANDIDATE', 'SOS Responder Candidate'), ('SOS_NEW_RESPONDER_INTEREST', 'SOS New Responder Interest'), ('BOOKING_REQUEST', 'Booking Request'), ('BOOKING_CONFIRMED', 'Booking Confirmed'), ('BOOKING_COMPLETED', 'Booking Completed'), ('PAYMENT_RECEIVED', 'Payment Received'), ('BADGE_UNLOCK', 'Badge Unlock'), ('POINTS_AWARDED', 'Points Awarded'), ('TIP_VERIFIED', 'Tip Verified'), ('NEW_MESSAGE', 'New Message'), ('SUBSCRIPTION_EXPIRING', 'Subscription Expiring'), ('SHOWCASE_ORDER', 'Showcase Order'), ('SHOWCASE_DELIVERED', 'Showcase Delivered'), ('LEVEL_UP', 'Level Up'), ('REVIEW_RECEIVED', 'Review Received')], max_length=30),
        ),
    ]
