# Generated by Django 5.0.6 on 2026-05-31 16:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=300)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('category', models.CharField(choices=[('Safari', 'Safari'), ('Food', 'Food & Drink'), ('Culture', 'Culture'), ('Nightlife', 'Night Life'), ('Beach', 'Beach'), ('Adventure', 'Adventure'), ('Art', 'Art & Craft')], max_length=20)),
                ('price_range', models.CharField(blank=True, max_length=100, null=True)),
                ('price_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('price_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('today_moment_active', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('subscription_required', models.CharField(default='FREE', max_length=25)),
                ('views', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExperienceMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='experiences/')),
                ('is_primary', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='experiences.experience')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
