# Generated by Django 5.0.6 on 2026-06-03 13:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BettingPredictionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_team', models.CharField(max_length=100)),
                ('away_team', models.CharField(max_length=100)),
                ('league', models.CharField(max_length=50)),
                ('original_query', models.TextField(blank=True)),
                ('ai_message_id', models.CharField(blank=True, help_text='Link to AIMessage for context', max_length=50)),
                ('ai_thread_id', models.CharField(blank=True, help_text='Link to AIThread for conversation', max_length=50)),
                ('prediction_data', models.JSONField(blank=True, default=dict)),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Null = not deleted, timestamp = deleted', null=True)),
                ('delete_reason', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='betting_predictions_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='admin_ops_b_user_id_a451de_idx'), models.Index(fields=['user', 'league'], name='admin_ops_b_user_id_5018f8_idx'), models.Index(fields=['deleted_at'], name='admin_ops_b_deleted_0c621d_idx')],
            },
        ),
    ]
