# Generated by Django 5.0.6 on 2026-06-05 15:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_ops', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('ROLE_CHANGE', 'Role Change'), ('POINTS_AWARD', 'Points Award'), ('USER_SUSPENSION', 'User Suspension'), ('USER_ACTIVATION', 'User Activation'), ('MODERATION_ACTION', 'Moderation Action'), ('SOS_OVERRIDE', 'SOS Override'), ('SOS_RESOLVE', 'SOS Resolve'), ('SOS_CANCEL', 'SOS Cancel'), ('SOS_ESCALATE', 'SOS Escalate'), ('ADMIN_ACTION', 'Admin Action'), ('B2B_EXPORT', 'B2B Export'), ('ANALYTICS_ACCESS', 'Analytics Access'), ('SYSTEM_OVERRIDE', 'System Override'), ('BOOKING_OVERRIDE', 'Booking Override'), ('PAYMENT_OVERRIDE', 'Payment Override')], db_index=True, max_length=50)),
                ('action_description', models.CharField(max_length=200)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('before_state', models.JSONField(blank=True, default=dict, help_text='State before action')),
                ('after_state', models.JSONField(blank=True, default=dict, help_text='State after action')),
                ('reason', models.TextField(blank=True, help_text='Reason for the action')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional context')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(help_text='User who performed the action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs_as_actor', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(blank=True, help_text='User affected by the action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs_as_target', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['actor', 'created_at'], name='admin_ops_a_actor_i_4607ec_idx'), models.Index(fields=['target_user', 'created_at'], name='admin_ops_a_target__598bf1_idx'), models.Index(fields=['action_type', 'created_at'], name='admin_ops_a_action__764041_idx'), models.Index(fields=['-created_at'], name='admin_ops_a_created_e38918_idx')],
            },
        ),
    ]
