# Generated by Django 5.0.6 on 2026-06-06 17:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_ops', '0002_auditlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPageConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cta_background_image', models.URLField(blank=True, help_text='Background image for CTA section')),
                ('serengeti_image', models.URLField(blank=True, help_text='Image for Serengeti Safari experience card')),
                ('kilimanjaro_image', models.URLField(blank=True, help_text='Image for Kilimanjaro Trek experience card')),
                ('zanzibar_image', models.URLField(blank=True, help_text='Image for Zanzibar Beach experience card')),
                ('ngorongoro_image', models.URLField(blank=True, help_text='Image for Ngorongoro Crater experience card')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='landing_page_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Landing Page Configuration',
                'verbose_name_plural': 'Landing Page Configurations',
            },
        ),
    ]
