# Generated by Django 5.0.6 on 2026-06-08 06:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_ops', '0003_landingpageconfig'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of the reviewer', max_length=100)),
                ('role', models.CharField(help_text='Role/Title (e.g., Travel Blogger, Local Guide)', max_length=100)),
                ('avatar_letter', models.CharField(help_text='First letter for avatar', max_length=1)),
                ('text', models.TextField(help_text='Review text/testimonial')),
                ('rating', models.IntegerField(default=5, help_text='Rating out of 5')),
                ('location', models.CharField(help_text='Location where experience happened', max_length=100)),
                ('color', models.CharField(default='#F5A623', help_text='Color for the testimonial card (hex code)', max_length=7)),
                ('profile_url', models.URLField(blank=True, help_text='Optional link to user profile or external site')),
                ('is_featured', models.BooleanField(default=True, help_text='Show on landing page')),
                ('display_order', models.IntegerField(default=0, help_text='Order of display (lower = first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testimonial_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
                'ordering': ['display_order', '-created_at'],
            },
        ),
    ]
