# Generated by Django 5.0.6 on 2026-06-09 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_ops', '0004_testimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='avatar',
            field=models.URLField(blank=True, help_text='Avatar image URL (Cloudinary)'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='avatar_letter',
            field=models.CharField(blank=True, help_text='First letter for avatar (fallback)', max_length=1),
        ),
    ]
