# Generated by Django 5.0.6 on 2026-06-09 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_ops', '0005_testimonial_avatar_alter_testimonial_avatar_letter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landingpageconfig',
            name='kilimanjaro_image',
        ),
        migrations.AddField(
            model_name='landingpageconfig',
            name='stats_background_image',
            field=models.URLField(blank=True, help_text='Background image for Stats section'),
        ),
    ]
