# Generated by Django 5.0.6 on 2026-06-09 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_ops', '0006_remove_landingpageconfig_kilimanjaro_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpageconfig',
            name='download_background_image',
            field=models.URLField(blank=True, help_text='Background image for Download section'),
        ),
        migrations.AddField(
            model_name='landingpageconfig',
            name='features_background_image',
            field=models.URLField(blank=True, help_text='Background image for Features section'),
        ),
        migrations.AddField(
            model_name='landingpageconfig',
            name='kilicarebet_background_image',
            field=models.URLField(blank=True, help_text='Background image for KilicareBet Preview section'),
        ),
        migrations.AddField(
            model_name='landingpageconfig',
            name='pricing_background_image',
            field=models.URLField(blank=True, help_text='Background image for Pricing section'),
        ),
        migrations.AddField(
            model_name='landingpageconfig',
            name='testimonials_background_image',
            field=models.URLField(blank=True, help_text='Background image for Testimonials section'),
        ),
    ]
