# Generated by Django 5.0.6 on 2026-06-18 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_ops', '0007_landingpageconfig_download_background_image_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LandingPageConfig',
        ),
    ]
