# Generated by Django 5.0.6 on 2026-06-10 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_chat', '0002_aithread_moment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraipreference',
            name='preferred_language',
            field=models.CharField(choices=[('sw', 'Kiswahili'), ('en', 'English'), ('fr', 'Français'), ('es', 'Español'), ('de', 'Deutsch'), ('ar', 'العربية'), ('zh', '中文')], default='sw', max_length=3),
        ),
    ]
