# Generated by Django 5.0.6 on 2026-06-15 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_alter_message_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='attachment',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
