# Generated by Django 5.0.6 on 2026-05-31 17:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('FREE', 'Free'), ('BASIC_CREATOR', 'Basic Creator'), ('BUSINESS_CREATOR', 'Business Creator'), ('PRO_GUIDE', 'Pro Guide'), ('TOURIST_PREMIUM', 'Tourist Premium'), ('SPORTS_PREMIUM', 'Sports Premium')], max_length=25, unique=True)),
                ('display_name', models.CharField(max_length=60)),
                ('description', models.TextField(blank=True)),
                ('price_weekly', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_monthly', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_experiences', models.IntegerField(default=2)),
                ('max_showcase_items', models.IntegerField(default=0)),
                ('has_verified_badge', models.BooleanField(default=False)),
                ('has_booking_system', models.BooleanField(default=False)),
                ('has_analytics', models.BooleanField(default=False)),
                ('has_featured_placement', models.BooleanField(default=False)),
                ('visibility_multiplier', models.FloatField(default=1.0)),
                ('has_ai_unlimited', models.BooleanField(default=False)),
                ('has_offline_mode', models.BooleanField(default=False)),
                ('has_predictions_all', models.BooleanField(default=False)),
                ('has_whatsapp_alerts', models.BooleanField(default=False)),
                ('trial_days', models.IntegerField(default=14)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('TRIAL', 'Trial'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], default='TRIAL', max_length=15)),
                ('billing_cycle', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('free', 'Free')], default='monthly', max_length=10)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField()),
                ('trial_end_date', models.DateField(blank=True, null=True)),
                ('auto_renew', models.BooleanField(default=True)),
                ('mpesa_subscription_id', models.CharField(blank=True, max_length=100, null=True)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='subscriptions.subscriptionplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='TZS', max_length=5)),
                ('mpesa_transaction_code', models.CharField(blank=True, max_length=50, null=True)),
                ('mpesa_checkout_request_id', models.CharField(blank=True, max_length=100, null=True)),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=15)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='subscriptions.usersubscription')),
            ],
        ),
    ]
