# Generated by Django 5.0.6 on 2026-06-05 17:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('MOMENT', 'Moment'), ('TIP', 'Tip'), ('EXPERIENCE', 'Experience'), ('USER', 'User'), ('COMMENT', 'Comment'), ('MESSAGE', 'Message')], max_length=20)),
                ('content_id', models.PositiveIntegerField(help_text='ID of the reported content')),
                ('reason', models.CharField(choices=[('INAPPROPRIATE', 'Inappropriate Content'), ('SPAM', 'Spam'), ('HARASSMENT', 'Harassment'), ('MISINFORMATION', 'Misinformation'), ('COPYRIGHT', 'Copyright Violation'), ('SCAM', 'Scam/Fraud'), ('VIOLENCE', 'Violence'), ('HATE_SPEECH', 'Hate Speech'), ('OTHER', 'Other')], max_length=20)),
                ('description', models.TextField(help_text='Detailed description of the issue')),
                ('evidence_urls', models.JSONField(default=list, help_text='List of evidence URLs/screenshots')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved - No Action'), ('REJECTED', 'Rejected - No Violation'), ('HIDDEN', 'Hidden - Violation Found'), ('DELETED', 'Deleted - Severe Violation'), ('FEATURED', 'Featured - High Quality'), ('RESTORED', 'Restored - Reinstated')], default='PENDING', max_length=20)),
                ('moderator_notes', models.TextField(blank=True, help_text="Moderator's notes")),
                ('action_taken', models.CharField(blank=True, help_text='Action taken by moderator', max_length=50)),
                ('priority', models.PositiveIntegerField(default=5, help_text='1=highest, 10=lowest')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_owner', models.ForeignKey(help_text='User who owns the reported content', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_received', to=settings.AUTH_USER_MODEL)),
                ('moderator', models.ForeignKey(blank=True, help_text='Moderator who handled this report', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_moderated', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(help_text='User who submitted the report', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Moderation Report',
                'verbose_name_plural': 'Moderation Reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ModerationAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('APPROVE', 'Approve Content'), ('REJECT', 'Reject Report'), ('HIDE', 'Hide Content'), ('DELETE', 'Delete Content'), ('FEATURE', 'Feature Content'), ('RESTORE', 'Restore Content'), ('SUSPEND_USER', 'Suspend User'), ('WARN_USER', 'Warn User'), ('BULK_DELETE', 'Bulk Delete'), ('BULK_HIDE', 'Bulk Hide')], max_length=20)),
                ('content_type', models.CharField(blank=True, max_length=20)),
                ('content_id', models.PositiveIntegerField(blank=True, null=True)),
                ('reason', models.TextField(help_text='Reason for the action')),
                ('notes', models.TextField(blank=True, help_text='Additional notes')),
                ('before_state', models.JSONField(blank=True, default=dict)),
                ('after_state', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('moderator', models.ForeignKey(help_text='Moderator who took the action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_actions', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(blank=True, help_text='User affected by the action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_actions_received', to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(blank=True, help_text='Related report (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions', to='moderation.report')),
            ],
            options={
                'verbose_name': 'Moderation Action',
                'verbose_name_plural': 'Moderation Actions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['status', '-created_at'], name='moderation__status_282342_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['content_type', 'content_id'], name='moderation__content_1b6680_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['priority', '-created_at'], name='moderation__priorit_29d524_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['reporter', '-created_at'], name='moderation__reporte_350be5_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['content_owner', '-created_at'], name='moderation__content_84a0a3_idx'),
        ),
        migrations.AddIndex(
            model_name='moderationaction',
            index=models.Index(fields=['moderator', '-created_at'], name='moderation__moderat_59647a_idx'),
        ),
        migrations.AddIndex(
            model_name='moderationaction',
            index=models.Index(fields=['target_user', '-created_at'], name='moderation__target__045127_idx'),
        ),
        migrations.AddIndex(
            model_name='moderationaction',
            index=models.Index(fields=['action_type', '-created_at'], name='moderation__action__989271_idx'),
        ),
        migrations.AddIndex(
            model_name='moderationaction',
            index=models.Index(fields=['report', '-created_at'], name='moderation__report__71c4f7_idx'),
        ),
    ]
