# Generated by Django 5.0.6 on 2026-06-05 15:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sosresponse',
            options={'ordering': ['created_at']},
        ),
        migrations.AddField(
            model_name='sosalert',
            name='admin_override_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sosalert',
            name='admin_override_by',
            field=models.ForeignKey(blank=True, help_text='Admin who overrode this alert', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sos_overrides', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sosalert',
            name='admin_override_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sosalert',
            name='avg_response_time_minutes',
            field=models.FloatField(blank=True, help_text='Average time to respond', null=True),
        ),
        migrations.AddField(
            model_name='sosalert',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sosalert',
            name='escalated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sosalert',
            name='escalated_by',
            field=models.ForeignKey(blank=True, help_text='User who escalated this alert', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sos_escalations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sosalert',
            name='escalation_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sosalert',
            name='first_response_at',
            field=models.DateTimeField(blank=True, help_text='Time of first responder', null=True),
        ),
        migrations.AddField(
            model_name='sosalert',
            name='priority',
            field=models.PositiveIntegerField(default=5, help_text='1=highest priority, 10=lowest'),
        ),
        migrations.AddField(
            model_name='sosalert',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='sosresponse',
            name='onsite_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sosalert',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('RESPONDING', 'Responding'), ('ESCALATED', 'Escalated'), ('RESOLVED', 'Resolved'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=15),
        ),
        migrations.AddIndex(
            model_name='sosalert',
            index=models.Index(fields=['status', '-created_at'], name='sos_sosaler_status_f0fe82_idx'),
        ),
        migrations.AddIndex(
            model_name='sosalert',
            index=models.Index(fields=['severity', '-created_at'], name='sos_sosaler_severit_eb06e9_idx'),
        ),
        migrations.AddIndex(
            model_name='sosalert',
            index=models.Index(fields=['priority', '-created_at'], name='sos_sosaler_priorit_5661c1_idx'),
        ),
        migrations.AddIndex(
            model_name='sosalert',
            index=models.Index(fields=['latitude', 'longitude'], name='sos_sosaler_latitud_081515_idx'),
        ),
        migrations.AddIndex(
            model_name='sosresponse',
            index=models.Index(fields=['alert', 'created_at'], name='sos_sosresp_alert_i_7c582d_idx'),
        ),
        migrations.AddIndex(
            model_name='sosresponse',
            index=models.Index(fields=['responder', '-created_at'], name='sos_sosresp_respond_3edbe3_idx'),
        ),
    ]
