# Generated by Django 5.0.6 on 2026-06-16 08:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0004_alter_message_attachment'),
        ('sos', '0004_add_chat_room_to_sosalert'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Skip AlterField for chat_room since constraint already exists
        migrations.CreateModel(
            name='SOSEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('SOS_CREATED', 'SOS Created'), ('GUIDE_RESPONDED', 'Guide Responded'), ('CHAT_MESSAGE', 'Chat Message'), ('STATUS_CHANGE', 'Status Changed'), ('SOS_RESOLVED', 'SOS Resolved'), ('SOS_CANCELLED', 'SOS Cancelled'), ('SOS_ESCALATED', 'SOS Escalated')], db_index=True, help_text='Type of event', max_length=20)),
                ('data', models.JSONField(blank=True, default=dict, help_text='Additional event metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, help_text='User who triggered this event', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sos_events', to=settings.AUTH_USER_MODEL)),
                ('alert', models.ForeignKey(help_text='The SOS alert this event belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='events', to='sos.sosalert')),
                ('message', models.ForeignKey(blank=True, help_text='Related chat message (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sos_events', to='messaging.message')),
                ('response', models.ForeignKey(blank=True, help_text='Related SOS response (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='sos.sosresponse')),
            ],
            options={
                'verbose_name': 'SOS Event',
                'verbose_name_plural': 'SOS Events',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['alert', '-created_at'], name='sos_soseven_alert_i_91f459_idx'), models.Index(fields=['event_type', '-created_at'], name='sos_soseven_event_t_92559b_idx'), models.Index(fields=['actor', '-created_at'], name='sos_soseven_actor_i_300ff4_idx')],
            },
        ),
    ]
