# Generated by Django 5.0.6 on 2026-06-17 12:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0004_alter_message_attachment'),
        ('sos', '0005_alter_sosalert_chat_room_sosevent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sosalert',
            name='assigned_at',
            field=models.DateTimeField(blank=True, help_text='When primary responder was assigned', null=True),
        ),
        migrations.AddField(
            model_name='sosalert',
            name='primary_responder',
            field=models.ForeignKey(blank=True, help_text='The guide currently assigned as primary responder', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sosresponse',
            name='accepted_at',
            field=models.DateTimeField(blank=True, help_text='When guide accepted assignment', null=True),
        ),
        migrations.AddField(
            model_name='sosresponse',
            name='arrived_at',
            field=models.DateTimeField(blank=True, help_text='When guide arrived on site', null=True),
        ),
        migrations.AddField(
            model_name='sosresponse',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text='When guide completed the rescue', null=True),
        ),
        migrations.AddField(
            model_name='sosresponse',
            name='guide_status',
            field=models.CharField(choices=[('INTERESTED', 'Interested'), ('ACCEPTED', 'Accepted'), ('ON_THE_WAY', 'On The Way'), ('ARRIVED', 'Arrived'), ('COMPLETED', 'Completed')], default='INTERESTED', max_length=15),
        ),
        migrations.AddField(
            model_name='sosresponse',
            name='on_the_way_at',
            field=models.DateTimeField(blank=True, help_text='When guide started traveling', null=True),
        ),
        # Skip AlterField for chat_room - constraint already exists in database
        # migrations.AlterField(
        #     model_name='sosalert',
        #     name='chat_room',
        #     field=models.ForeignKey(blank=True, help_text='Chat room for ongoing conversation between tourist and guide', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sos_alerts', to='messaging.chatroom'),
        # ),
        migrations.AlterField(
            model_name='sosalert',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('ASSIGNED', 'Assigned'), ('ON_THE_WAY', 'On The Way'), ('ON_SITE', 'On Site'), ('COMPLETED', 'Completed'), ('ESCALATED', 'Escalated'), ('RESOLVED', 'Resolved'), ('CANCELLED', 'Cancelled'), ('HANDOFF', 'Handoff')], default='ACTIVE', max_length=15),
        ),
        migrations.AlterField(
            model_name='sosevent',
            name='event_type',
            field=models.CharField(choices=[('SOS_CREATED', 'SOS Created'), ('GUIDE_INTERESTED', 'Guide Interested'), ('GUIDE_ASSIGNED', 'Guide Assigned'), ('GUIDE_ACCEPTED', 'Guide Accepted'), ('GUIDE_ON_THE_WAY', 'Guide On The Way'), ('GUIDE_ARRIVED', 'Guide Arrived'), ('GUIDE_COMPLETED', 'Guide Completed'), ('CHAT_MESSAGE', 'Chat Message'), ('STATUS_CHANGE', 'Status Changed'), ('SOS_RESOLVED', 'SOS Resolved'), ('SOS_CANCELLED', 'SOS Cancelled'), ('SOS_ESCALATED', 'SOS Escalated'), ('PRIMARY_REASSIGNED', 'Primary Reassigned')], db_index=True, help_text='Type of event', max_length=20),
        ),
    ]
