# Generated by Django 5.0.6 on 2026-06-17 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0004_alter_message_attachment'),
        ('sos', '0006_sosalert_assigned_at_sosalert_primary_responder_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sosalert',
            name='chat_room',
            field=models.ForeignKey(blank=True, help_text='Chat room for ongoing conversation between tourist and guide', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sos_alerts', to='messaging.chatroom'),
        ),
    ]
