# Generated by Django 5.0.6 on 2026-06-18 03:35

from django.db import migrations


def remove_duplicate_responses(apps, schema_editor):
    """Remove duplicate SOSResponse entries before adding unique constraint."""
    SOSResponse = apps.get_model('sos', 'SOSResponse')
    
    # Find and remove duplicate (alert, responder) pairs
    # Keep the most recent response for each pair
    from django.db.models import Count, Max
    
    duplicates = SOSResponse.objects.values('alert', 'responder').annotate(
        count=Count('id'),
        max_id=Max('id')
    ).filter(count__gt=1)
    
    for dup in duplicates:
        # Delete all but the most recent response
        SOSResponse.objects.filter(
            alert_id=dup['alert'],
            responder_id=dup['responder']
        ).exclude(id=dup['max_id']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0004_alter_message_attachment'),
        ('sos', '0007_alter_sosalert_chat_room'),
    ]

    operations = [
        # Remove duplicate data before adding constraints
        migrations.RunPython(remove_duplicate_responses, migrations.RunPython.noop),
    ]
