# Generated by Django 5.0.6 on 2026-06-18 03:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0004_alter_message_attachment'),
        ('sos', '0008_sosalert_sos_sosaler_primary_95e4b3_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='sosalert',
            index=models.Index(fields=['primary_responder', '-created_at'], name='sos_sosaler_primary_95e4b3_idx'),
        ),
        migrations.AddIndex(
            model_name='sosalert',
            index=models.Index(fields=['user', '-created_at'], name='sos_sosaler_user_id_c7fc27_idx'),
        ),
        migrations.AddIndex(
            model_name='sosevent',
            index=models.Index(fields=['alert', 'event_type', '-created_at'], name='sos_soseven_alert_i_bb79c6_idx'),
        ),
        migrations.AddIndex(
            model_name='sosresponse',
            index=models.Index(fields=['alert', 'responder'], name='sos_sosresp_alert_i_edb21f_idx'),
        ),
        migrations.AddIndex(
            model_name='sosresponse',
            index=models.Index(fields=['guide_status', '-created_at'], name='sos_sosresp_guide_s_aef510_idx'),
        ),
        migrations.AddIndex(
            model_name='sosresponse',
            index=models.Index(fields=['alert', 'guide_status'], name='sos_sosresp_alert_i_0af68a_idx'),
        ),
        migrations.AddConstraint(
            model_name='sosalert',
            constraint=models.CheckConstraint(check=models.Q(('primary_responder__isnull', True), ('status__in', ['ASSIGNED', 'ON_THE_WAY', 'ON_SITE', 'COMPLETED', 'HANDOFF']), _connector='OR'), name='primary_responder_only_when_assigned', violation_error_message='Primary responder can only be set when incident is in assigned state'),
        ),
        migrations.AddConstraint(
            model_name='sosresponse',
            constraint=models.UniqueConstraint(fields=('alert', 'responder'), name='unique_responder_per_alert', violation_error_message='A guide can only respond to an incident once'),
        ),
    ]
