# Generated by Django 5.0.6 on 2026-06-18 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sos', '0009_sosalert_sos_sosaler_primary_95e4b3_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sosevent',
            name='event_type',
            field=models.CharField(choices=[('SOS_CREATED', 'SOS Created'), ('GUIDE_INTERESTED', 'Guide Interested'), ('GUIDE_ASSIGNED', 'Guide Assigned'), ('GUIDE_ACCEPTED', 'Guide Accepted'), ('GUIDE_ON_THE_WAY', 'Guide On The Way'), ('GUIDE_ARRIVED', 'Guide Arrived'), ('GUIDE_COMPLETED', 'Guide Completed'), ('CHAT_MESSAGE', 'Chat Message'), ('STATUS_CHANGE', 'Status Changed'), ('SOS_RESOLVED', 'SOS Resolved'), ('SOS_CANCELLED', 'SOS Cancelled'), ('SOS_ESCALATED', 'SOS Escalated'), ('PRIMARY_REASSIGNED', 'Primary Reassigned'), ('ADMIN_INTERVENTION', 'Admin Intervention')], db_index=True, help_text='Type of event', max_length=20),
        ),
    ]
