# Generated by Django 5.0.6 on 2026-06-18 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sos', '0010_alter_sosevent_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sosresponse',
            name='guide_status',
            field=models.CharField(choices=[('INTERESTED', 'Interested'), ('ACCEPTED', 'Accepted'), ('ON_THE_WAY', 'On The Way'), ('ARRIVED', 'Arrived'), ('COMPLETED', 'Completed'), ('UNABLE_TO_CONTINUE', 'Unable To Continue')], default='INTERESTED', max_length=20),
        ),
    ]
