# Generated by Django 5.0.6 on 2026-06-19 09:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0004_alter_message_attachment'),
        ('sos', '0011_alter_sosresponse_guide_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='sosalert',
            name='primary_responder_only_when_assigned',
        ),
        migrations.AlterField(
            model_name='sosalert',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('ASSIGNED', 'Assigned'), ('ON_THE_WAY', 'On The Way'), ('ARRIVED', 'Arrived'), ('ESCALATED', 'Escalated'), ('RESOLVED', 'Resolved'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=15),
        ),
        migrations.AlterField(
            model_name='sosevent',
            name='event_type',
            field=models.CharField(choices=[('SOS_CREATED', 'SOS Created'), ('GUIDE_INTERESTED', 'Guide Interested'), ('GUIDE_ASSIGNED', 'Guide Assigned'), ('GUIDE_ACCEPTED', 'Guide Accepted'), ('GUIDE_ON_THE_WAY', 'Guide On The Way'), ('GUIDE_ARRIVED', 'Guide Arrived'), ('GUIDE_COMPLETED', 'Guide Completed'), ('PRIMARY_FAILED', 'Primary Failed'), ('STANDBY_PROMOTED', 'Standby Promoted'), ('CHAT_MESSAGE', 'Chat Message'), ('MESSAGE_SENT', 'Message Sent'), ('STATUS_CHANGE', 'Status Changed'), ('SOS_RESOLVED', 'SOS Resolved'), ('SOS_CANCELLED', 'SOS Cancelled'), ('SOS_ESCALATED', 'SOS Escalated'), ('PRIMARY_REASSIGNED', 'Primary Reassigned'), ('ADMIN_ACTION', 'Admin Action'), ('ADMIN_INTERVENTION', 'Admin Intervention')], db_index=True, help_text='Type of event', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='sosalert',
            constraint=models.CheckConstraint(check=models.Q(('primary_responder__isnull', True), ('status__in', ['ASSIGNED', 'ON_THE_WAY', 'ARRIVED']), _connector='OR'), name='primary_responder_only_when_assigned', violation_error_message='Primary responder can only be set when incident is in assigned state'),
        ),
    ]
