# Generated by Django 5.0.6 on 2026-06-20 07:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0004_alter_message_attachment'),
        ('sos', '0012_remove_sosalert_primary_responder_only_when_assigned_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='sosalert',
            name='primary_responder_only_when_assigned',
        ),
        migrations.AlterField(
            model_name='sosalert',
            name='status',
            field=models.CharField(choices=[('WAITING_FOR_RESPONDER', 'Waiting For Responder'), ('ACTIVE', 'Active'), ('ASSIGNED', 'Assigned'), ('ON_THE_WAY', 'On The Way'), ('ARRIVED', 'Arrived'), ('ESCALATED', 'Escalated'), ('RESOLVED', 'Resolved'), ('CANCELLED', 'Cancelled')], default='WAITING_FOR_RESPONDER', max_length=25),
        ),
        migrations.AddConstraint(
            model_name='sosalert',
            constraint=models.CheckConstraint(check=models.Q(('primary_responder__isnull', True), ('status__in', ['ASSIGNED', 'ON_THE_WAY', 'ARRIVED', 'ACTIVE']), _connector='OR'), name='primary_responder_only_when_assigned', violation_error_message='Primary responder can only be set when incident is in assigned state'),
        ),
    ]
