# Generated by Django 5.0.6 on 2026-05-29 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpcode',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
