# Generated by Django 5.0.6 on 2026-06-05 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passport', '0002_alter_badge_options_alter_userbadge_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='passportprofile',
            name='qr_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
