# Generated by Django 5.0.6 on 2026-06-05 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passport', '0003_passportprofile_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='passportprofile',
            name='achievement_stamps',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
