# Generated by Django 5.0.6 on 2026-06-05 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passport', '0005_alter_pointstransaction_action_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passportprofile',
            name='qr_code',
            field=models.TextField(blank=True, null=True),
        ),
    ]
