# Generated by Django 5.0.6 on 2026-05-31 05:42

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moments', '0002_alter_moment_media_alter_moment_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='moment',
            name='audio',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Background music for this moment', max_length=255, null=True),
        ),
    ]
