# Generated by Django 5.0.6 on 2026-06-23 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moments', '0004_remove_momentcomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moment',
            name='audio',
        ),
        migrations.RemoveField(
            model_name='moment',
            name='media',
        ),
        migrations.RemoveField(
            model_name='moment',
            name='media_type',
        ),
        migrations.RemoveField(
            model_name='moment',
            name='thumbnail',
        ),
        migrations.CreateModel(
            name='MomentMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('audio', 'Audio')], max_length=10)),
                ('url', models.URLField(max_length=500)),
                ('public_id', models.CharField(max_length=255)),
                ('duration', models.FloatField(blank=True, help_text='Duration in seconds for audio/video', null=True)),
                ('width', models.IntegerField(blank=True, help_text='Width in pixels for image/video', null=True)),
                ('height', models.IntegerField(blank=True, help_text='Height in pixels for image/video', null=True)),
                ('file_size', models.BigIntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('moment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_items', to='moments.moment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
