# Generated by Django 5.0.6 on 2026-06-21 08:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_notifications', models.BooleanField(default=True, help_text='Enable email notifications')),
                ('push_notifications', models.BooleanField(default=True, help_text='Enable push notifications')),
                ('sms_notifications', models.BooleanField(default=False, help_text='Enable SMS notifications')),
                ('profile_visibility', models.CharField(choices=[('PUBLIC', 'Public - Visible to everyone'), ('FOLLOWERS', 'Followers Only'), ('PRIVATE', 'Private - Hidden from everyone')], default='PUBLIC', help_text='Who can view your profile', max_length=20)),
                ('show_location', models.BooleanField(default=True, help_text='Show your location on map')),
                ('allow_follow_requests', models.BooleanField(default=True, help_text='Allow others to follow you')),
                ('language', models.CharField(choices=[('sw', 'Kiswahili'), ('en', 'English'), ('fr', 'Français'), ('es', 'Español'), ('de', 'Deutsch'), ('ar', 'العربية'), ('zh', '中文')], default='sw', help_text='Preferred language', max_length=5)),
                ('theme', models.CharField(choices=[('dark', 'Dark'), ('light', 'Light'), ('auto', 'Auto (System)')], default='dark', help_text='App theme preference', max_length=10)),
                ('enable_ai_chat', models.BooleanField(default=True, help_text='Enable AI Chat feature')),
                ('enable_predictions', models.BooleanField(default=True, help_text='Enable Sports Predictions feature')),
                ('enable_sos', models.BooleanField(default=True, help_text='Enable SOS Emergency feature')),
                ('enable_showcase', models.BooleanField(default=True, help_text='Enable Virtual Showcase feature')),
                ('enable_moments', models.BooleanField(default=True, help_text='Enable Social Moments feature')),
                ('content_filter', models.CharField(choices=[('NONE', 'No Filter'), ('LOW', 'Low Sensitivity'), ('MEDIUM', 'Medium Sensitivity'), ('HIGH', 'High Sensitivity')], default='MEDIUM', help_text='Content filtering sensitivity', max_length=20)),
                ('auto_download_media', models.BooleanField(default=False, help_text='Auto-download media on mobile data')),
                ('low_data_mode', models.BooleanField(default=False, help_text='Reduce data usage (lower quality images)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Settings',
                'verbose_name_plural': 'User Settings',
            },
        ),
    ]
