# Generated by Django 5.0.6 on 2026-06-01 06:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='B2BClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('company_type', models.CharField(choices=[('HOTEL', 'Hotel'), ('SAFARI', 'Safari Company'), ('BOARD', 'Tourism Board'), ('AIRLINE', 'Airline'), ('OTHER', 'Other')], default='HOTEL', max_length=50)),
                ('location', models.CharField(max_length=200)),
                ('contact_email', models.EmailField(max_length=254)),
                ('is_verified', models.BooleanField(default=False)),
                ('subscription_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='b2b_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
